services:
  - type: web
    name: scraper-agent
    env: python
    rootDirectory: ScraperAgent
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      npx playwright install --with-deps
    startCommand: |
      uvicorn server:app --host 0.0.0.0 --port $PORT