services:
  - type: web
    name: scraper-agent
    env: python
    plan: free
    root: ScraperAgent
    autoDeploy: true
    buildCommand: |
      cd ScraperAgent
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      playwright install --with-deps
    startCommand: |
      cd ScraperAgent
      uvicorn server:app --host 0.0.0.0 --port $PORT